apiVersion: demo.mycompany.com/v1
kind: ConfigMapApp
metadata:
  name: my-nginx-app
spec:
  image: nginx
  replicas: 2
  configData:
    app.conf: "server { listen 80; }"
    database.conf: "host=localhost"
